#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xset r rate 300 50 &	# Speed xrate up
#unclutter &		# Remove mouse when idle
#dunst &			# dunst for notifications

autostart="xcompmgr dunst unclutter"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

sct 3500 &
xbacklight -set 25 &
