#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/.xprofile because that
# file is run automatically if someone uses a display manager (login screen)
# and so they are needed there. To prevent doubling up commands, I source them
# here with the line below.

[ -f ~/.xprofile ] && . "$HOME"/.xprofile


###PERSONAL EDIT###
i3

xset s off
xset -dpms
xset s noblank
xset r rate 300 50
setxkbmap -option caps:super
