#!/bin/sh

# Profile file. Runs on login. Environmental variables are set here.

export PATH="$HOME/.local/bin:$HOME/py:$HOME/.local/usr/local/bin:$HOME/.local/usr/bin:$HOME/.local/share/gem/ruby/3.0.0/bin:$HOME/.cargo/bin:$PATH"
export XBPS_DISTDIR="$HOME/workbench/void-packages"

#Allow user-wide installations for npm
export npm_config_prefix="$HOME/.local"

# Default programs:
export EDITOR="nvim"
export TERMINAL="xterm"
export BROWSER="firefox"
export READER="zathura"
export FILE="ranger"

# ~/ Clean-up:
export LESSHISTFILE="-"

export BAT_THEME="Dracula"

[ ! -f ~/.config/shortcutrc ] && shortcuts >/dev/null 2>&1

echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && . "$HOME/.bashrc"

# Start graphical server if i3 not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx
. "$HOME/.cargo/env"
