#!/bin/sh
mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove" \
	xq="xbps-query" \
	v="$EDITOR" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ffmpeg="ffmpeg -hide_banner"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
