#!/bin/sh

alias mpv='mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)' \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove" \
	xq="xbps-query" \
	v='$EDITOR' \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ffmpeg="ffmpeg -hide_banner" \
	cat='bat' \
	la='ls -A' \
	l='ls -1' \
	ll='ls -lt' \
	xbacklight='sudo xbacklight' \
	ipconfig='curl -4 -sS ipconfig.io' \
	cp='cp -v' \
	mv='mv -v' \
	mkdir='mkdir -v' \
	rm='rm -v' \
	vv='cd ~/Videos && ls -A *' \
	pp='cd ~/Pictures && ls -A *' \
	mm='cd ~/Music && ls -A !(data-music)' \
	ipa='ip -c a' \
	wget='wget --hsts-file="$XDG_DATA_HOME"/wget-hsts' \
	scd='echo "YOU USED SCD, BE CAREFUL" ; cd' \
	adb='HOME="$XDG_DATA_HOME"/android adb' \
	k=kubectl \
	t=task \
	tl='task --list-all' \
	sshvps='ssh debian@vps.vpn -p8022' \
	sshpve='ssh pve.vpn -p8022' \
	sshwin='ssh win.vpn -p8022' \
